apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
    username: c3R1ZHltYXRlCg== # "studymate" | base64
    password: c2hhaGFyYW1pdHNoYWhhZgo= # "shaharamitshahaf" | base64

