---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: studymate-frontend
  labels:
    application/name: studymate
    application/component: frontend
spec:
  selector:
    matchLabels:
      application/name: studymate
  replicas: 1
  template:
    metadata:
      labels:
        application/name: studymate
        application/component: frontend
    spec:
      containers:
        - name: studymate-frontend
          image: ghcr.io/shahafs12/studymate-client:1.0
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
          env:
            - name: REACT_APP_API_BASE_URL
              value: "http://studymate-backend:8080/"

---
apiVersion: v1
kind: Service
metadata:
  name: studymate-frontend
  labels:
    application/name: studymate
#  annotations:
#    service.beta.kubernetes.io/azure-dns-label-name: studymate
#
#    # so it resolves to:
    # studymate.israelcentral.cloudapp.azure.com
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000

  selector:
    application/component: frontend