---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: studymate-backend
  labels:
    application/name: studymate
    application/component: backend
spec:
  selector:
    matchLabels:
      application/name: studymate
      application/component: backend
  replicas: 1
  template:
    metadata:
      labels:
        application/name: studymate
        application/component: backend
    spec:
      containers:
        - name: studymate
          image: ghcr.io/shahafs12/studymate-app:3.1.2
          imagePullPolicy: Always

          ports:
            - containerPort: 8080
          env:
            - name: MONGODB_HOST
              value: "mongodb.default.svc.cluster.local"
            - name: MONGODB_PORT
              value: "27017"
            - name: MONGODB_DATABASE
              value: "studymate"
            - name: MONGODB_USERNAME
              value: "studymate"
            - name: MONGODB_PASSWORD
              value: "shaharamitshahaf"

     #     volumeMounts:
      #      - name: persistent-storage
       #       mountPath: /data

   #   volumes:
    #    - name: persistent-storage
     #     persistentVolumeClaim:
      #      claimName: studymate-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: studymate-backend
  labels:
    application/name: studymate
    application/component: backend
spec:
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer
  selector:
    application/component: backend