---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: studymate-backend
  labels:
    application/name: studymate
    application/component: backend
spec:
  selector:
    matchLabels:
      application/name: studymate
      application/component: backend
  replicas: 1
  template:
    metadata:
      labels:
        application/name: studymate
        application/component: backend
    spec:
      containers:
        - name: studymate
          image: ghcr.io/shahafs12/studymate-server:1.0

          ports:
            - containerPort: 3000

          volumeMounts:
            - name: persistent-storage
              mountPath: /data

          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: password
            - name: MONGO_HOST
              value: "mongodb"
            - name: MONGO_PORT
              value: "27017"

      volumes:
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: studymate-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: studymate-backend
  labels:
    application/name: studymate
    application/component: backend
spec:

  ports:
    - port: 3000
      targetPort: 3000
  selector:
    application/component: backend