spring:
    data:
        mongodb:
            host: localhost #mongodb.default.svc.cluster.local
            port: 27017
          #  database: studymate
          #  username: studymate
          #  password: shaharamitshahaf


jwt:
    secret: "044561dc31ea927d424cf34c400e6c2433e6488aaa797f37a8a2a33c50303d91"
    expiration: 86400000
